image:
  file: .gitpod.Dockerfile

    # List the ports you want to expose and what to do when they are served. See https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview

# List the start up tasks. You can start them in parallel in multiple terminals. See https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: |
      mkdir -p .vscode;
      cat << EOF > .vscode/settings.json
      {
        "python.pythonPath": "$(which python)",
        "python.testing.pytestArgs": [
          "tests"
        ],
        "python.testing.unittestEnabled": false,
        "python.testing.nosetestsEnabled": false,
        "python.testing.pytestEnabled": true
      }
      EOF
      python -m pip install -r requirements.txt;
      sudo docker-up;

vscode:
  extensions:
    - littlefoxteam.vscode-python-test-adapter
