---
- name: Install aptitude using apt
  apt: name=aptitude state=latest update_cache=yes force_apt_get=yes

- name: Get env file content
  set_fact:
    env_vars: "{{ item }}"
  with_file:
    - ".env"

- name: Install required system packages
  apt: name={{ item }} state=latest update_cache=yes
  loop:
    - curl
    - ca-certificates
    - apt-transport-https
    - software-properties-common
    - python3-pip
    - python3-setuptools
    - virtualenv
    - git

- name: install gpg
  apt:
    name: gnupg
    update_cache: yes    

