---
- name: Install required system packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop:
    - curl
    - python3-pip
    - python3-setuptools
    - git
    - gpg

- name: Get env file content
  set_fact:
    env_vars: "{{ item }}"
  with_file:
    - ".env"
