version: "3"

services:

  ldap:
    image: osixia/openldap
    restart: always
    environment: 
      LDAP_DOMAIN: "${LDAP_DOMAIN:-example.org}"
      LDAP_BASE_DN: "${LDAP_BASE_DN:-dc=example,dc=org}"
      LDAP_ADMIN_PASSWORD: "${LDAP_ADMIN_PASSWORD:-changeme}"
      LDAP_CONFIG_PASSWORD: "${LDAP_CONFIG_PASSWORD:-changeme}"
      LDAP_TLS: "true"
    ports:
      - 1389:389
    volumes:
      - ./ldif:/container/service/slapd/assets/config/bootstrap/ldif/custom
    command: --loglevel debug --copy-service

  database:
    build: database
    restart: always
    volumes:
      - irods_database:/var/lib/postgresql/
      - ./database/init.sh:/docker-entrypoint-initdb.d/init.sh:ro
    environment:
      MY_DB: $IRODS_DB_NAME
      MY_USER: $IRODS_DB_USER
      MY_PASSWORD: $IRODS_DB_PASS
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
 
  icat:
    build:
      context: irods
      dockerfile: Dockerfile.centos
      args:
        IRODS_VERSION: ${IRODS_VERSION}
        IRODS_USER: ${IRODS_USER}
    hostname: icat
    restart: always
    links: 
      - database
    ports:
      - "$IRODS_SERVICE_PORT:$IRODS_SERVICE_PORT"
    environment:
      DATABASE_TYPE: "postgres"
      IRODS_DB_HOST: database
      IRODS_DB_NAME: $IRODS_DB_NAME
      IRODS_DB_PORT: $IRODS_DB_PORT
      IRODS_DB_USER: $IRODS_DB_USER
      IRODS_DB_PASS: $IRODS_DB_PASS
      IRODS_RANGE_FROM: $IRODS_RANGE_FROM
      IRODS_RANGE_TILL: $IRODS_RANGE_TILL
      IRODS_HOST: icat
      IRODS_ZONE: $IRODS_ZONE
      IRODS_USER: $IRODS_USER
      IRODS_PASS: $IRODS_PASS
      IRODS_SERVICE_NAME: $IRODS_SERVICE_NAME
      IRODS_SERVICE_GROUP: $IRODS_SERVICE_GROUP
      IRODS_SERVICE_PORT: $IRODS_SERVICE_PORT
      IRODS_CONTROL_PORT: $IRODS_CONTROL_PORT
    volumes:
      - ~/.ssh/id_rsa.pub:/tmp/authorized_keys
      - ./irods/entrypoint.sh:/usr/local/bin/entrypoint.sh
      - ./irods/genresp.sh:/usr/local/bin/genresp.sh
      - ./irods_environment:/usr/local/etc/irods
      - ./pam_irods.py:/etc/pam.d/pam_irods.py
    command:
      - /bin/sh
      - -c
      - |
        echo 'Starting irods...'
        cat /tmp/authorized_keys >> /home/${IRODS_USER}/.ssh/authorized_keys
        echo 'auth required pam_python.so /etc/pam.d/pam_irods.py' > /etc/pam.d/irods
        /bin/bash /usr/local/bin/entrypoint.sh
    
  icommands:
    build:
      context: irods
      dockerfile: Dockerfile.centos
      args:
        IRODS_VERSION: ${IRODS_VERSION}
        IRODS_USER: ${IRODS_USER}
    hostname: icommands
    restart: always
    links: 
      - icat
    ports:
      - "2222:22"
    environment:
      IRODS_HOST: icat
      IRODS_PORT: ${IRODS_SERVICE_PORT:-1247}
      IRODS_ZONE: ${IRODS_ZONE:-tempZone}
      IRODS_USER: ${IRODS_USER:-rods}
      IRODS_PASS: ${IRODS_PASS:-password}
    volumes:
      - ~/.ssh/id_rsa.pub:/tmp/authorized_keys
      - ./irods_environment:/usr/local/etc/irods
    command:
      - /bin/sh
      - -c
      - |
        echo 'Starting icommands...'
        cat /tmp/authorized_keys >> /home/${IRODS_USER}/.ssh/authorized_keys
        /usr/sbin/sshd -D

volumes:
  irods_database:
    driver: local
