---
- name: Install docker packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop:
    - docker
    - docker-compose
  
- name: Install Docker Module for Python
  pip:
    name: docker